### PR TITLE
Fixed cache issue with steps that output empty layer

### LINKED ISSUE #71: Implicit caching doesn't work at all
The cached layers are never pulled and used during the build when implicit caching (the default) is on.

### PR DESCRIPTION
**Pull request by apourchet**
Steps like WORKDIR and USER that output no layers would never get pushed
to the cache/registry, and so the cache would always break on these
steps.

Resolves #71.

### CODE REVIEW

File: lib/builder/build_node.go [hunk 1]
```diff
@@ -105,13 +105,16 @@ func (n *buildNode) doCommit(cacheMgr cache.Manager, opts *buildOptions) error {
 		return fmt.Errorf("commit: %s", err)
 	}
 
-	// If the number of digestPairs is 0 or greater than 1 then we cannot push
+	// If the number of digestPairs is greater than 1 then we cannot push
 	// the resulting layer mappings to the distributed cache.
-	if len(n.digestPairs) != 1 {
+	var digestPair *image.DigestPair
```
Comment (evelynl94) [inline lib/builder/build_node.go]: maybe you should put all the if statements in one place - `n.pushCacheLayer`

File: lib/builder/build_node.go [hunk 2]
```diff
@@ -161,6 +165,8 @@ func (n *buildNode) pullCacheLayers(cacheMgr cache.Manager) bool {
 	if err != nil {
```
Comment (evelynl94) [inline lib/builder/build_node.go]: should this be `pullCacheLayer` ?

File: lib/cache/cache_manager.go [hunk 3]
```diff
@@ -149,12 +154,15 @@ func (manager *registryCacheManager) PushCache(cacheID string, digestPair *image
 		manager.Lock()
 		defer manager.Unlock()
 
-		if err := manager.registryClient.PushLayer(digestPair.GzipDescriptor.Digest); err != nil {
-			manager.pushErrors.Add(fmt.Errorf("push layer %s: %s", digestPair.GzipDescriptor.Digest, err))
-			return
+		entry := _cacheEmptyEntry
+		if digestPair != nil {
+			entry = createEntry(digestPair.TarDigest, digestPair.GzipDescriptor.Digest)
```
Comment (evelynl94) [inline lib/cache/cache_manager.go]: maybe `createEntry` can create an empty entry or non-empty entry and push it?
